init:
- appveyor version

image: Visual Studio 2017

version: 2.0.{build}

configuration: AppStore

#shallow_clone: true
platform: Any CPU

# restore packages
before_build:
  - nuget restore

build:
  verbosity: minimal
